[package]
name = "lang"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-map = "2.7.3"
itertools = "0.14.0"
nom = "8.0.0"
nom_locate = "5.0.0"
nom-supreme = { path = "./lib/nom-supreme", version="0.8.0" }
nom-language = "0.1.0"
datatest-stable = "0.3.2"
assert_cmd = "2.0.17"
strum = { version = "0.28.0", features = ["derive"] }

[[test]]
name = "runner"
harness = false
